import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Nav from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | RYU PORTFOLIO",
    default: "RYU PORTFOLIO",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className} bg`}>
        <div className="grid grid-cols-1 grid-rows-[40px_1fr] lg:grid-rows-[60px_1fr] gap-0 h-screen">
          <Header />
          <main className="h-full" >{children}</main>
        </div>
        <Nav />
      </body>
    </html>
  );
}
